### ISSUE TITLE
Import fails with JSON::ParserError

### ISSUE THREAD

**Issue by oefe** [takafumir/wunder2reminders#2]
Import of a fresh export from Wunderlist fails with a JSON ParserError:

```
$ ./wunder2reminders.rb ../Wunderlist-20200223/Tasks.json 
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/c (JSON::ParserError)se': 822: unexpected token at '﻿[
  {
    "id": 1234567890,
    "title": "inbox",
```
(...skipping most of the JSON for brevity and privacy...)
```
  }
]'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:335:in `load'
	from ./wunder2reminders.rb:7:in `<main>'
```

Apparently, Wunderlist changed their export file format.

**Comment by loelkes** [comment]
I wrote a Python version and made a PR. Maybe this helps, see #3
